import typing, clr, abc
from JAStudio.Core.UI.Web.Kanji import KanjiNoteRenderer
from JAStudio.Core.UI.Web.Sentence import SentenceNoteRenderer
from JAStudio.Core.UI.Web.Vocab import VocabNoteRenderer
from System import IEquatable_1, IDisposable
from Compze.DependencyInjection.Microsoft import MicrosoftContainerBuilder
from System.Collections.Generic import Dictionary_2, List_1
from JAStudio.Core.Note import NoteId, ExternalNoteIdMap, NoteServices
from JAStudio.Core.Note.Collection import CardStudyingStatus, JPCollection
from JAStudio.Core.Configuration import JapaneseConfig, ConfigurationStore
from JAStudio.Core.TaskRunners import TaskRunner, BackgroundTaskManager
from Compze.DependencyInjection.Abstractions import IComponentRegistrar, IRootResolver
from JAStudio.Core.Batches import LocalNoteUpdater
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory

class AnkiHTMLRenderers:
    @property
    def KanjiNoteRenderer(self) -> KanjiNoteRenderer: ...
    @property
    def SentenceNoteRenderer(self) -> SentenceNoteRenderer: ...
    @property
    def VocabNoteRenderer(self) -> VocabNoteRenderer: ...


class AppBootstrapper(abc.ABC):
    @staticmethod
    def PrepareForTests() -> AppBootstrapper.BootstrapPlan: ...
    @staticmethod
    def PrepareProduction(deps: IEnvironmentSpecificDependenciesRegistrar) -> AppBootstrapper.BootstrapPlan: ...

    class BootstrapPlan(IEquatable_1[AppBootstrapper.BootstrapPlan]):
        def __init__(self, Builder: MicrosoftContainerBuilder) -> None: ...
        @property
        def Builder(self) -> MicrosoftContainerBuilder: ...
        @Builder.setter
        def Builder(self, value: MicrosoftContainerBuilder) -> MicrosoftContainerBuilder: ...
        def Deconstruct(self, Builder: clr.Reference[MicrosoftContainerBuilder]) -> None: ...
        def GetHashCode(self) -> int: ...
        def __eq__(self, left: AppBootstrapper.BootstrapPlan, right: AppBootstrapper.BootstrapPlan) -> bool: ...
        def __ne__(self, left: AppBootstrapper.BootstrapPlan, right: AppBootstrapper.BootstrapPlan) -> bool: ...
        def ToString(self) -> str: ...
        # Skipped Equals due to it being static, abstract and generic.

        Equals : Equals_MethodGroup
        class Equals_MethodGroup:
            @typing.overload
            def __call__(self, other: AppBootstrapper.BootstrapPlan) -> bool:...
            @typing.overload
            def __call__(self, obj: typing.Any) -> bool:...




class BackendData:
    def __init__(self, idMappings: Dictionary_2[int, NoteId], studyingStatuses: List_1[CardStudyingStatus]) -> None: ...
    @property
    def IdMappings(self) -> Dictionary_2[int, NoteId]: ...
    @property
    def StudyingStatuses(self) -> List_1[CardStudyingStatus]: ...


class CoreApp(IDisposable):
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Config(self) -> JapaneseConfig: ...
    @classmethod
    @property
    def IsTesting(cls) -> bool: ...
    @property
    def Paths(self) -> IEnvironmentPaths: ...
    @property
    def Services(self) -> TemporaryServiceCollection: ...
    def Dispose(self) -> None: ...


class IBackendDataLoader(typing.Protocol):
    @abc.abstractmethod
    def Load(self, taskRunner: TaskRunner) -> BackendData: ...


class IEnvironmentPaths(typing.Protocol):
    @property
    def AddonRootDir(self) -> str: ...
    @property
    def AnkiMediaDir(self) -> str: ...
    @property
    def DatabaseDir(self) -> str: ...
    @property
    def MediaDir(self) -> str: ...
    @property
    def MetadataDir(self) -> str: ...
    @property
    def UserFilesDir(self) -> str: ...


class IEnvironmentSpecificDependenciesRegistrar(typing.Protocol):
    @abc.abstractmethod
    def WireEnvironmentSpecificServices(self, registrar: IComponentRegistrar) -> None: ...


class StringExtensions(abc.ABC):
    InvisibleSpace : str
    @staticmethod
    def ExtractCommaSeparatedValues(input: str) -> List_1[str]: ...
    @staticmethod
    def FirstNumber(input: str) -> str: ...
    @staticmethod
    def PadToLength(value: str, targetLength: int, spaceScaling: float = ...) -> str: ...
    @staticmethod
    def ReplaceWord(word: str, replacement: str, text: str) -> str: ...
    @staticmethod
    def StripHtmlMarkup(input: str) -> str: ...


class TemporaryServiceCollection:
    @property
    def AnkiHTMLRenderers(self) -> AnkiHTMLRenderers: ...
    @property
    def BackgroundTaskManager(self) -> BackgroundTaskManager: ...
    @property
    def ConfigurationStore(self) -> ConfigurationStore: ...
    @property
    def CoreApp(self) -> CoreApp: ...
    @property
    def ExternalNoteIdMap(self) -> ExternalNoteIdMap: ...
    @classmethod
    @property
    def Instance(cls) -> TemporaryServiceCollection: ...
    @classmethod
    @Instance.setter
    def Instance(cls, value: TemporaryServiceCollection) -> TemporaryServiceCollection: ...
    @property
    def LocalNoteUpdater(self) -> LocalNoteUpdater: ...
    @property
    def NoteServices(self) -> NoteServices: ...
    @property
    def Services(self) -> IRootResolver: ...
    @property
    def TaskRunner(self) -> TaskRunner: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    # Skipped Resolve due to it being static, abstract and generic.

    Resolve : Resolve_MethodGroup
    class Resolve_MethodGroup:
        def __getitem__(self, t:typing.Type[Resolve_1_T1]) -> Resolve_1[Resolve_1_T1]: ...

        Resolve_1_T1 = typing.TypeVar('Resolve_1_T1')
        class Resolve_1(typing.Generic[Resolve_1_T1]):
            Resolve_1_T = TemporaryServiceCollection.Resolve_MethodGroup.Resolve_1_T1
            def __call__(self) -> Resolve_1_T:...



