<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>disable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4"/>
      <PackageReference Include="pythonnet" Version="3.0.5"/>
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.Internals.SystemCE\Compze.Internals.SystemCE.csproj" />
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.Threading\Compze.Threading.csproj" />
   </ItemGroup>

</Project>