import typing, abc
from JAStudio.Core.Note import NoteId, KanjiNote
from System.Collections.Generic import IEnumerable_1, IReadOnlyCollection_1, IReadOnlyList_1, List_1
from JAStudio.Core.TaskRunners import TaskRunner, BackgroundTaskManager
from JAStudio.Core import IEnvironmentPaths
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.NoteFields import MediaType
from System import IEquatable_1

class AlreadyStoredFile:
    def __init__(self, existing: MediaAttachment, noteId: NoteId) -> None: ...
    @property
    def Existing(self) -> MediaAttachment: ...
    @property
    def NoteId(self) -> NoteId: ...


class AudioAttachment(MediaAttachment):
    def __init__(self) -> None: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...


class CopyrightStatus(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Unknown : CopyrightStatus # 0
    Commercial : CopyrightStatus # 1
    Free : CopyrightStatus # 2


class ImageAttachment(MediaAttachment):
    def __init__(self) -> None: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...


class ImportRule:
    def __init__(self, prefix: SourceTag, fieldName: str, targetDirectory: str, copyright: CopyrightStatus) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def FieldName(self) -> str: ...
    @property
    def Prefix(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class ImportRulesCE(abc.ABC):
    @staticmethod
    def TryResolve(this: IEnumerable_1[ImportRule], sourceTag: SourceTag, fieldName: str) -> ImportRule: ...


class KanjiMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : KanjiMediaField # 0
    Image : KanjiMediaField # 1


class MediaAttachment(abc.ABC):
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...


class MediaFileIndex:
    @typing.overload
    def __init__(self, mediaRoot: str, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager) -> None: ...
    @typing.overload
    def __init__(self, paths: IEnvironmentPaths, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager) -> None: ...
    @property
    def All(self) -> IReadOnlyCollection_1[MediaAttachment]: ...
    @property
    def Count(self) -> int: ...
    def Build(self) -> None: ...
    def ContainsByOriginalFileName(self, originalFileName: str) -> bool: ...
    def GetAudioAttachments(self, rawValue: str) -> IReadOnlyList_1[AudioAttachment]: ...
    def GetImageAttachments(self, rawValue: str) -> IReadOnlyList_1[ImageAttachment]: ...
    def Register(self, attachment: MediaAttachment) -> None: ...
    def TryGetByOriginalFileName(self, originalFileName: str) -> MediaAttachment: ...


class MediaImportAnalyzer:
    def __init__(self, ankiMediaDir: str, index: MediaFileIndex) -> None: ...
    def AnalyzeKanji(self, notes: IReadOnlyList_1[KanjiNote], rules: IReadOnlyList_1[ImportRule]) -> MediaImportPlan: ...
    def AnalyzeSentences(self, notes: IReadOnlyList_1[SentenceNote], rules: IReadOnlyList_1[ImportRule]) -> MediaImportPlan: ...
    def AnalyzeVocab(self, notes: IReadOnlyList_1[VocabNote], rules: IReadOnlyList_1[ImportRule]) -> MediaImportPlan: ...


class MediaImportExecutor:
    def __init__(self, storageService: MediaStorageService, taskRunner: TaskRunner) -> None: ...
    def Execute(self, plan: MediaImportPlan) -> None: ...


class MediaImportPlan:
    def __init__(self) -> None: ...
    @property
    def AlreadyStored(self) -> List_1[AlreadyStoredFile]: ...
    @property
    def FilesToImport(self) -> List_1[PlannedFileImport]: ...
    @property
    def Missing(self) -> List_1[MissingFile]: ...


class MediaImportRulePersistence:
    def __init__(self) -> None: ...
    @staticmethod
    def Load(paths: IEnvironmentPaths) -> PersistedImportRules: ...
    @staticmethod
    def Save(rules: PersistedImportRules, paths: IEnvironmentPaths) -> None: ...


class MediaStorageService:
    @typing.overload
    def __init__(self, mediaRoot: str, index: MediaFileIndex) -> None: ...
    @typing.overload
    def __init__(self, paths: IEnvironmentPaths, index: MediaFileIndex) -> None: ...
    def StoreFile(self, sourceFilePath: str, targetDirectory: str, originalFileName: str, mediaType: MediaType) -> None: ...


class MissingFile:
    def __init__(self, fileName: str, noteId: NoteId, fieldName: str) -> None: ...
    @property
    def FieldName(self) -> str: ...
    @property
    def FileName(self) -> str: ...
    @property
    def NoteId(self) -> NoteId: ...


class PersistedImportRules:
    def __init__(self) -> None: ...
    @property
    def KanjiRules(self) -> List_1[ImportRule]: ...
    @KanjiRules.setter
    def KanjiRules(self, value: List_1[ImportRule]) -> List_1[ImportRule]: ...
    @property
    def SentenceRules(self) -> List_1[ImportRule]: ...
    @SentenceRules.setter
    def SentenceRules(self, value: List_1[ImportRule]) -> List_1[ImportRule]: ...
    @property
    def VocabRules(self) -> List_1[ImportRule]: ...
    @VocabRules.setter
    def VocabRules(self, value: List_1[ImportRule]) -> List_1[ImportRule]: ...


class PlannedFileImport:
    def __init__(self, sourcePath: str, targetDirectory: str, copyright: CopyrightStatus, sourceTag: SourceTag, originalFileName: str, noteId: NoteId, mediaType: MediaType) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def MediaType(self) -> MediaType: ...
    @property
    def NoteId(self) -> NoteId: ...
    @property
    def OriginalFileName(self) -> str: ...
    @property
    def SourcePath(self) -> str: ...
    @property
    def SourceTag(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class SentenceMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : SentenceMediaField # 0
    Screenshot : SentenceMediaField # 1


class SourceTag(IEquatable_1[SourceTag]):
    @property
    def Segments(self) -> IReadOnlyList_1[str]: ...
    def Contains(self, descendant: SourceTag) -> bool: ...
    def GetHashCode(self) -> int: ...
    def IsContainedIn(self, ancestor: SourceTag) -> bool: ...
    def __eq__(self, left: SourceTag, right: SourceTag) -> bool: ...
    def __ne__(self, left: SourceTag, right: SourceTag) -> bool: ...
    @staticmethod
    def Parse(value: str) -> SourceTag: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: SourceTag) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class VocabMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    AudioFirst : VocabMediaField # 0
    AudioSecond : VocabMediaField # 1
    AudioTts : VocabMediaField # 2
    Image : VocabMediaField # 3
    UserImage : VocabMediaField # 4

