import typing, clr, abc
from JAStudio.Core.Note import NoteId, KanjiNote
from System.Collections.Generic import List_1, IReadOnlyCollection_1, IReadOnlyList_1
from System import IEquatable_1, Guid
from JAStudio.Core.TaskRunners import TaskRunner, BackgroundTaskManager
from JAStudio.Core import IEnvironmentPaths
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.NoteFields import MediaType

class AlreadyStoredFile:
    def __init__(self, existing: MediaAttachment, noteId: NoteId) -> None: ...
    @property
    def Existing(self) -> MediaAttachment: ...
    @property
    def NoteId(self) -> NoteId: ...


class AudioAttachment(MediaAttachment):
    def __init__(self) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @Copyright.setter
    def Copyright(self, value: CopyrightStatus) -> CopyrightStatus: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def Id(self) -> MediaFileId: ...
    @Id.setter
    def Id(self, value: MediaFileId) -> MediaFileId: ...
    @property
    def NoteIds(self) -> List_1[NoteId]: ...
    @NoteIds.setter
    def NoteIds(self, value: List_1[NoteId]) -> List_1[NoteId]: ...
    @property
    def NoteSourceTag(self) -> SourceTag: ...
    @NoteSourceTag.setter
    def NoteSourceTag(self, value: SourceTag) -> SourceTag: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...
    @property
    def Tts(self) -> TtsInfo: ...
    @Tts.setter
    def Tts(self, value: TtsInfo) -> TtsInfo: ...


class CopyrightStatus(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Unknown : CopyrightStatus # 0
    Commercial : CopyrightStatus # 1
    Free : CopyrightStatus # 2


class ImageAttachment(MediaAttachment):
    def __init__(self) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @Copyright.setter
    def Copyright(self, value: CopyrightStatus) -> CopyrightStatus: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def Id(self) -> MediaFileId: ...
    @Id.setter
    def Id(self, value: MediaFileId) -> MediaFileId: ...
    @property
    def NoteIds(self) -> List_1[NoteId]: ...
    @NoteIds.setter
    def NoteIds(self, value: List_1[NoteId]) -> List_1[NoteId]: ...
    @property
    def NoteSourceTag(self) -> SourceTag: ...
    @NoteSourceTag.setter
    def NoteSourceTag(self, value: SourceTag) -> SourceTag: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...


class KanjiImportRule:
    def __init__(self, prefix: SourceTag, field: KanjiMediaField, targetDirectory: str, copyright: CopyrightStatus) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def Field(self) -> KanjiMediaField: ...
    @property
    def Prefix(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class KanjiMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : KanjiMediaField # 0
    Image : KanjiMediaField # 1


class MediaAttachment(abc.ABC):
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @Copyright.setter
    def Copyright(self, value: CopyrightStatus) -> CopyrightStatus: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def Id(self) -> MediaFileId: ...
    @Id.setter
    def Id(self, value: MediaFileId) -> MediaFileId: ...
    @property
    def NoteIds(self) -> List_1[NoteId]: ...
    @NoteIds.setter
    def NoteIds(self, value: List_1[NoteId]) -> List_1[NoteId]: ...
    @property
    def NoteSourceTag(self) -> SourceTag: ...
    @NoteSourceTag.setter
    def NoteSourceTag(self, value: SourceTag) -> SourceTag: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...


class MediaFileId(IEquatable_1[MediaFileId]):
    def __init__(self, value: Guid) -> None: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def Value(self) -> Guid: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def New() -> MediaFileId: ...
    def __eq__(self, left: MediaFileId, right: MediaFileId) -> bool: ...
    def __ne__(self, left: MediaFileId, right: MediaFileId) -> bool: ...
    @staticmethod
    def Parse(value: str) -> MediaFileId: ...
    def ToString(self) -> str: ...
    @staticmethod
    def TryParse(value: str, result: clr.Reference[MediaFileId]) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaFileId) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaFileIndex:
    @typing.overload
    def __init__(self, mediaRoot: str, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager) -> None: ...
    @typing.overload
    def __init__(self, paths: IEnvironmentPaths, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager) -> None: ...
    @property
    def All(self) -> IReadOnlyCollection_1[MediaAttachment]: ...
    @property
    def Count(self) -> int: ...
    def Build(self) -> None: ...
    def Contains(self, id: MediaFileId) -> bool: ...
    def ContainsByOriginalFileName(self, originalFileName: str) -> bool: ...
    def GetNoteMedia(self, noteId: NoteId) -> NoteMedia: ...
    def Register(self, attachment: MediaAttachment) -> None: ...
    def TryGetAttachment(self, id: MediaFileId) -> MediaAttachment: ...
    def TryGetByOriginalFileName(self, originalFileName: str) -> MediaAttachment: ...
    def TryGetInfo(self, id: MediaFileId) -> MediaFileInfo: ...
    def TryResolve(self, id: MediaFileId) -> str: ...


class MediaFileInfo:
    def __init__(self, id: MediaFileId, fullPath: str, originalFileName: str, extension: str) -> None: ...
    @property
    def Extension(self) -> str: ...
    @property
    def FullPath(self) -> str: ...
    @property
    def Id(self) -> MediaFileId: ...
    @property
    def OriginalFileName(self) -> str: ...


class MediaImportAnalyzer:
    def __init__(self, ankiMediaDir: str, index: MediaFileIndex) -> None: ...
    def AnalyzeKanji(self, notes: IReadOnlyList_1[KanjiNote], rules: IReadOnlyList_1[KanjiImportRule]) -> MediaImportPlan: ...
    def AnalyzeSentences(self, notes: IReadOnlyList_1[SentenceNote], rules: IReadOnlyList_1[SentenceImportRule]) -> MediaImportPlan: ...
    def AnalyzeVocab(self, notes: IReadOnlyList_1[VocabNote], rules: IReadOnlyList_1[VocabImportRule]) -> MediaImportPlan: ...
    def IsAlreadyStored(self, originalFileName: str) -> bool: ...


class MediaImportExecutor:
    def __init__(self, storageService: MediaStorageService, taskRunner: TaskRunner) -> None: ...
    def Execute(self, plan: MediaImportPlan) -> None: ...


class MediaImportPlan:
    def __init__(self) -> None: ...
    @property
    def AlreadyStored(self) -> List_1[AlreadyStoredFile]: ...
    @property
    def FilesToImport(self) -> List_1[PlannedFileImport]: ...
    @property
    def Missing(self) -> List_1[MissingFile]: ...


class MediaImportRulePersistence:
    def __init__(self) -> None: ...
    @staticmethod
    def Load(paths: IEnvironmentPaths) -> PersistedImportRules: ...
    @staticmethod
    def Save(rules: PersistedImportRules, paths: IEnvironmentPaths) -> None: ...


class MediaImportRuleSet:
    def __init__(self, vocabRules: List_1[VocabImportRule], sentenceRules: List_1[SentenceImportRule], kanjiRules: List_1[KanjiImportRule]) -> None: ...
    def TryResolveKanji(self, sourceTag: SourceTag, field: KanjiMediaField) -> KanjiImportRule: ...
    def TryResolveSentence(self, sourceTag: SourceTag, field: SentenceMediaField) -> SentenceImportRule: ...
    def TryResolveVocab(self, sourceTag: SourceTag, field: VocabMediaField) -> VocabImportRule: ...


class MediaStorageService:
    @typing.overload
    def __init__(self, mediaRoot: str, index: MediaFileIndex) -> None: ...
    @typing.overload
    def __init__(self, paths: IEnvironmentPaths, index: MediaFileIndex) -> None: ...
    def AddNoteIdToExisting(self, existing: MediaAttachment, noteId: NoteId) -> None: ...
    def Exists(self, id: MediaFileId) -> bool: ...
    def StoreFile(self, sourceFilePath: str, targetDirectory: str, sourceTag: SourceTag, originalFileName: str, noteId: NoteId, mediaType: MediaType, copyright: CopyrightStatus, tts: TtsInfo = ...) -> MediaFileId: ...
    def TryResolve(self, id: MediaFileId) -> str: ...


class MissingFile:
    def __init__(self, fileName: str, noteId: NoteId, fieldName: str) -> None: ...
    @property
    def FieldName(self) -> str: ...
    @property
    def FileName(self) -> str: ...
    @property
    def NoteId(self) -> NoteId: ...


class NoteMedia:
    def __init__(self, audio: IReadOnlyList_1[AudioAttachment], images: IReadOnlyList_1[ImageAttachment]) -> None: ...
    @property
    def Audio(self) -> IReadOnlyList_1[AudioAttachment]: ...
    @classmethod
    @property
    def Empty(cls) -> NoteMedia: ...
    @property
    def Images(self) -> IReadOnlyList_1[ImageAttachment]: ...


class PersistedImportRules:
    def __init__(self) -> None: ...
    @property
    def KanjiRules(self) -> List_1[KanjiImportRule]: ...
    @KanjiRules.setter
    def KanjiRules(self, value: List_1[KanjiImportRule]) -> List_1[KanjiImportRule]: ...
    @property
    def SentenceRules(self) -> List_1[SentenceImportRule]: ...
    @SentenceRules.setter
    def SentenceRules(self, value: List_1[SentenceImportRule]) -> List_1[SentenceImportRule]: ...
    @property
    def VocabRules(self) -> List_1[VocabImportRule]: ...
    @VocabRules.setter
    def VocabRules(self, value: List_1[VocabImportRule]) -> List_1[VocabImportRule]: ...


class PlannedFileImport:
    def __init__(self, sourcePath: str, targetDirectory: str, copyright: CopyrightStatus, sourceTag: SourceTag, originalFileName: str, noteId: NoteId, mediaType: MediaType) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def MediaType(self) -> MediaType: ...
    @property
    def NoteId(self) -> NoteId: ...
    @property
    def OriginalFileName(self) -> str: ...
    @property
    def SourcePath(self) -> str: ...
    @property
    def SourceTag(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class SentenceImportRule:
    def __init__(self, prefix: SourceTag, field: SentenceMediaField, targetDirectory: str, copyright: CopyrightStatus) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def Field(self) -> SentenceMediaField: ...
    @property
    def Prefix(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class SentenceMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : SentenceMediaField # 0
    Screenshot : SentenceMediaField # 1


class SidecarSerializer(abc.ABC):
    AudioSidecarExtension : str
    AudioSidecarGlob : str
    ImageSidecarExtension : str
    ImageSidecarGlob : str
    @staticmethod
    def BuildAudioSidecarPath(mediaFilePath: str) -> str: ...
    @staticmethod
    def BuildImageSidecarPath(mediaFilePath: str) -> str: ...
    @staticmethod
    def DeserializeAudio(json: str) -> AudioAttachment: ...
    @staticmethod
    def DeserializeImage(json: str) -> ImageAttachment: ...
    @staticmethod
    def IsSidecarFile(filePath: str) -> bool: ...
    @staticmethod
    def ReadAudioSidecar(sidecarPath: str) -> AudioAttachment: ...
    @staticmethod
    def ReadImageSidecar(sidecarPath: str) -> ImageAttachment: ...
    @staticmethod
    def SerializeAudio(attachment: AudioAttachment) -> str: ...
    @staticmethod
    def SerializeImage(attachment: ImageAttachment) -> str: ...
    @staticmethod
    def WriteAudioSidecar(sidecarPath: str, attachment: AudioAttachment) -> None: ...
    @staticmethod
    def WriteImageSidecar(sidecarPath: str, attachment: ImageAttachment) -> None: ...


class SourceTag(IEquatable_1[SourceTag]):
    @property
    def Segments(self) -> IReadOnlyList_1[str]: ...
    def Contains(self, descendant: SourceTag) -> bool: ...
    def GetHashCode(self) -> int: ...
    def IsContainedIn(self, ancestor: SourceTag) -> bool: ...
    def __eq__(self, left: SourceTag, right: SourceTag) -> bool: ...
    def __ne__(self, left: SourceTag, right: SourceTag) -> bool: ...
    @staticmethod
    def Parse(value: str) -> SourceTag: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: SourceTag) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class TtsInfo:
    def __init__(self, engine: str, voice: str, version: str) -> None: ...
    @property
    def Engine(self) -> str: ...
    @property
    def Version(self) -> str: ...
    @property
    def Voice(self) -> str: ...


class VocabImportRule:
    def __init__(self, prefix: SourceTag, field: VocabMediaField, targetDirectory: str, copyright: CopyrightStatus) -> None: ...
    @property
    def Copyright(self) -> CopyrightStatus: ...
    @property
    def Field(self) -> VocabMediaField: ...
    @property
    def Prefix(self) -> SourceTag: ...
    @property
    def TargetDirectory(self) -> str: ...


class VocabMediaField(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    AudioFirst : VocabMediaField # 0
    AudioSecond : VocabMediaField # 1
    AudioTts : VocabMediaField # 2
    Image : VocabMediaField # 3
    UserImage : VocabMediaField # 4

