<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>disable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\JAStudio.Core\JAStudio.Core.csproj" />
      <ProjectReference Include="..\JAStudio.Anki\JAStudio.Anki.csproj" />
      <ProjectReference Include="..\JAStudio.PythonInterop\JAStudio.PythonInterop.csproj" />
      <ProjectReference Include="..\JAStudio.UI\JAStudio.UI.csproj" />
      <ProjectReference Include="..\JAStudio.Web\JAStudio.Web.csproj" />
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.0.3" />
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.Internals.Logging\Compze.Internals.Logging.csproj" />
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.Internals.SystemCE\Compze.Internals.SystemCE.csproj" />
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.DependencyInjection\Compze.DependencyInjection.csproj" />
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.DependencyInjection.Microsoft\Compze.DependencyInjection.Microsoft.csproj" />
      <ProjectReference Include="..\..\..\submodules\Compze\src\Compze.DependencyInjection.Microsoft.Extensions.Hosting\Compze.DependencyInjection.Microsoft.Extensions.Hosting.csproj" />
   </ItemGroup>

</Project>
