import typing, abc
from JAStudio.Core.Configuration import IConfigDictSource
from System import Action_1, Exception, Action
from System.Collections.Generic import Dictionary_2
from JAStudio.Core.TaskRunners import IFatalErrorHandler, IUIThreadDispatcher, TaskProgressDialogViewModel

class AnkiConfigDictSource(IConfigDictSource):
    def __init__(self, json: str, updateCallback: Action_1[str]) -> None: ...
    def Load(self) -> Dictionary_2[str, typing.Any]: ...
    def Persist(self, json: str) -> None: ...


class AvaloniaFatalErrorHandler(IFatalErrorHandler):
    def __init__(self) -> None: ...
    def Handle(self, exception: Exception) -> None: ...


class AvaloniaUIThreadDispatcher(IUIThreadDispatcher):
    def __init__(self) -> None: ...
    def CurrentThreadIsUIThread(self) -> bool: ...
    def InvokeSynchronouslyOnUIThread(self, action: Action) -> None: ...
    def OnTaskRunnerInstantiated(self, viewModel: TaskProgressDialogViewModel) -> None: ...
    def PostToUIThread(self, action: Action) -> None: ...
    def PumpEventsToKeepUIResponsive(self) -> None: ...


class ShortcutFinger(abc.ABC):
    @staticmethod
    def Down1(text: str) -> str: ...
    @staticmethod
    def Down2(text: str) -> str: ...
    @staticmethod
    def Down3(text: str) -> str: ...
    @staticmethod
    def Down5(text: str) -> str: ...
    @staticmethod
    def Down6(text: str) -> str: ...
    @staticmethod
    def FingerByPriorityOrder(index: int, text: str) -> str: ...
    @staticmethod
    def Home1(text: str) -> str: ...
    @staticmethod
    def Home2(text: str) -> str: ...
    @staticmethod
    def Home3(text: str) -> str: ...
    @staticmethod
    def Home4(text: str) -> str: ...
    @staticmethod
    def Home5(text: str) -> str: ...
    @staticmethod
    def None(text: str) -> str: ...
    @staticmethod
    def Numpad(index: int, text: str) -> str: ...
    @staticmethod
    def Up1(text: str) -> str: ...
    @staticmethod
    def Up2(text: str) -> str: ...
    @staticmethod
    def Up3(text: str) -> str: ...
    @staticmethod
    def Up4(text: str) -> str: ...
    @staticmethod
    def Up5(text: str) -> str: ...

